task 2 is done
js-tasks-ru/js-20210126_stanislav71 pull request #2
Opened 2021-01-29 23:13 UTC by urab0t

implementation of the sortString  function 
implementation of the pick  function 
implementation of the omit  function

2021-02-01 09:50 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let clone_arr = [...arr]
в JS используется "camelCase" нотация, именования следует исправить. Также обратите внимание на использование `const` и `let`

2021-02-01 09:50 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        return clone_arr.sort(sortFunction).reverse()
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2021-02-01 09:52 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +        if(field in obj)
у оператора `in` который позволяет проверить наличие свойства в объекте есть побочный эффект: он проверяет как собственные так и унаследованные свойства, а на практике в большинстве случае речь идет про собственные свойства.

2021-02-01 09:52 UTC, dosandk requested changes
необходимо внести правки согласно комментариям.
проверьте использования `let` и `const`

2021-02-01 10:49 UTC, urab0t commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let clone_arr = [...arr]
Заменил переменные на константы, там где это было необходимо

2021-02-01 10:52 UTC, urab0t commented on 02-javascript-data-types/1-sort-strings/index.js
> +        return clone_arr.sort(sortFunction).reverse()
Реализовал сортировку без реверса

2021-02-01 10:53 UTC, urab0t commented on 02-javascript-data-types/2-pick/index.js
> +        if(field in obj)
Заменил проверку с in на `if(Object.keys(obj).includes(field))`

2021-02-02 13:25 UTC, dosandk approved these changes

2021-02-04 02:11 UTC, urab0t commented
added implementation of the 'create-getter', 'invert-object', 'trim-symbols', 'unic' functions from task-03

2021-02-04 14:47 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        for(const field of path.split('.')){
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2021-02-04 14:48 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +    return [...new Set(arr)];
подумайте какие есть преимущества у `Array.from` по сравнению с спред-синтаксисом:
```
return [...new Set(arr)]
```

2021-02-04 14:48 UTC, dosandk approved these changes
решения принимаются, посмотрите пожалуйста комментарии :mag:
особенно обратите внимание на решение `createGetter`

2021-02-04 15:08 UTC, merged